FROM node:13 as build

RUN mkdir -p /usr/app
WORKDIR /usr/app

COPY package*.json /usr/app/

RUN npm ci

COPY . /usr/app/


EXPOSE 3000

CMD ["npm", "build"]


FROM nginx:stable-alpine
COPY --from=build /usr/app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]