FROM node:13 as build

RUN mkdir -p /usr/app
WORKDIR /usr/app

COPY package*.json /usr/app/
COPY public  /usr/app

RUN npm ci
RUN chmod a+x /usr/app/node_modules/.bin/react-scripts
COPY . /usr/app/
RUN npm run build

COPY build /usr/app/


FROM nginx:stable-alpine
COPY --from=build /usr/app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]