version: '3'

services:
  database:
    container_name: rankingapp-database
    image: mongo:4.2.0
    ports: 
      - 1048:27017
    expose:
      - 27017

  backend:
    build: ./backend
    container_name: rankingapp-backend
    image: rankingapp-backend
    ports: 
      - 3001:3001
    expose: 
      - 3001
    depends_on: 
      - database

  frontend:
    build: ./frontend
    container_name: rankingapp-frontend
    image: rankingapp-frontend
    volumes: 
      - ./frontend:/usr/app/
    stdin_open: true
    ports:
      - 3000:3000
    expose:
      - 3000
    
    