version: '3'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: rankingapp-backend-prod
    image: rankingapp-backend-prod
    environment:
      - PORT
      - MONGOLAB_URL
      - SECRET
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
    ports: 
      - 3001:3001
    expose: 
      - 3001

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: rankingapp-frontend-prod
    image: rankingapp-frontend-prod
    stdin_open: true
    ports:
      - 80:80
    expose:
      - 80
      