# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
    - uses: actions/checkout@v2

    - name: Compose
      run: 
        docker-compose up -d
      env:
        PORT: ${{ secrets.PORT }}
        TEST_PORT: ${{ secrets.TEST_PORT }}
        SECRET: ${{ secrets.SECRET }}
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    - name: Backend audit
      run: 
        docker exec rankingapp-backend npm audit

    - name: Backend lint
      run: 
        docker exec rankingapp-backend npm run lint

    - name: Backend unit test
      run:
        docker exec rankingapp-backend npm run test:unit
      
    - name: Frontend audit
      run: 
        docker exec rankingapp-frontend npm audit

    - name: Frontend lint
      run: 
        docker exec rankingapp-frontend npm run lint

    - name: Frontend unit test
      run:
        docker exec rankingapp-frontend npm run test

    - name: End to end tests
      run:
        docker exec rankingapp-backend npm run test:e2e
    
    - name: Teardown
      run:
        docker-compose down

    - name: Build frontent prod
      if: github.ref == 'refs/heads/master'
      run: docker build -f ./frontend/Dockerfile.prod --tag rankingapp-frontend-prod
      